### ISSUE TITLE
Please add feature to navigate to variables

### ISSUE THREAD

**Issue by Chris2011** [nbphpcouncil/freemarker_NB_highlighting#3]
I have this inside my ftl file: ${data}, where data is a variable String data = "test", which was set inside a java file. It would be nice, if I can navigate through this variable via F12 or Ctrl + Click.

Regards

Chris

**Comment by Monomachus** [comment]
But what if the same ftl is reused from multiple places? Where to go than?

**Comment by Chris2011** [comment]
I asked a colleague to explain me how ftl works, because I didn't know how that works that we call a servlet to render the ftl file via runtime. I don't know whether there is an annotation for ftl to give them the model to navigate through it. So maybe we can close this.
